//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Session()
        {
            this.Ticket = new HashSet<Ticket>();
        }
    
        public int SessionID { get; set; }
        public int RoomID { get; set; }
        public int FilmID { get; set; }
        public System.DateTime SessionDate { get; set; }
    
        public virtual Film Film { get; set; }
        public virtual Room Room { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Ticket { get; set; }

        public Session(int roomID, int filmID, DateTime sessionDate)
        {
            RoomID = roomID;
            FilmID = filmID;
            SessionDate = sessionDate;
        }
    }
}
